### ISSUE TITLE
Synchronize with msgpack java artifact 0.7.1

### ISSUE THREAD

**Issue by david-bouyssie** [msgpack/msgpack-scala#22]
Do you plan to release a version targeting the msgpack java artifact 0.7.1 ?

**Comment by xerial** [comment]
In #25, we will release msgpack-java 0.8.x based version

**Comment by david-bouyssie** [comment]
Big thumbs up ;-)

The 2.12 is already visible on maven central (https://mvnrepository.com/artifact/org.msgpack/msgpack-scala).
However other Scala versions are not there yet. I guess it's just a matter of time?

**Comment by xerial** [comment]
I think it's visible now. Thanks

**Comment by david-bouyssie** [comment]
Great! Thank you so much!
